### PR TITLE
Dutch translations & wordlist

### PR DESCRIPTION
**Pull request by SEPPDROID**
Least i could to is create a dutch translation for padloc ;).

i later read the issue thread https://github.com/padloc/padloc/issues/248 and noticed that https://github.com/jhjacobs81 started on the dutch translations, sorry if i possibly interfered...

Wordlist is from opentaal under the licenses:
   A. BSD (revised version):
   - Full license text: http://creativecommons.org/licenses/BSD/legalcode
   - Summary: http://creativecommons.org/licenses/BSD/deed.en
   B. Creative Commons, Attribution 3.0 (unported)
   - Full license text: http://creativecommons.org/licenses/by/3.0/legalcode
   - Summary: http://creativecommons.org/licenses/by/3.0/deed.en

see readme

[README_nl_NL.txt](https://github.com/padloc/padloc/files/11852357/README_nl_NL.txt)

### CODE REVIEW

**Comment by MaKleSoft** [comment]
@SEPPDROID Thanks for your contribution! Unfortunately one of the tests failed, saying there are missing translations. Can you run `npm run locale:extract` and then add the missing translations? Thanks!

**Comment by SEPPDROID** [comment]
Thank you for pointing me in the right direc

> @SEPPDROID Thanks for your contribution! Unfortunately one of the tests failed, saying there are missing translations. Can you run `npm run locale:extract` and then add the missing translations? Thanks!

Thank you for pointing me into the right direction! sorry for the messy commits, i forgot i ran dev on my local machine and accidently added unnecessary lines.

should be good now, let me know if all is ok :)

**Comment by SEPPDROID** [comment]
ran locale, format & test and all seems to work for me. Same with a fresh clone from my fork.

**Comment by MaKleSoft** [comment]
@SEPPDROID Why did you close this? If you're struggling with the failing tests I can sort those out for you and merge this. Only with your permission of course.

**Comment by SEPPDROID** [comment]
> @SEPPDROID Why did you close this? If you're struggling with the failing tests I can sort those out for you and merge this. Only with your permission of course.

I ran a dev setup and fixed the issue  after the first fail. Then ran all the tests on my system again with everything passing, yet the check  test fails at translation. I'm lacking the knowledge and archived my repo for someone else to continue.

**Pull request closed without merging**
