### PR TITLE
Added PL_PWA_URL in example.env file

### PR DESCRIPTION
**Pull request by AmoghSaxena**
In this commit added *PL_PWA_URL* in example.env

As I cannot find it in https://raw.githubusercontent.com/padloc/padloc/main/docs/examples/config/example.env
also there are other people like me searching to change the URL name but cannot find the variable.

### CODE REVIEW

**Comment by BrunoBernardino** [comment]
@AmoghSaxena do you want to fix the github issue (seems the commit didn't have an email connected to it)? Otherwise I can just reject this and add the code in a PR myself.

**Comment by AmoghSaxena** [comment]
@BrunoBernardino Wait I'll fix this email issue.

**Comment by AmoghSaxena** [comment]
@BrunoBernardino Can you tell me which email is associate with this PR? As I am unable to figure it out that. 

I have already Signed the CLA 
image


Still I am seeing this as an issue.
Thanks in advance.

**Comment by BrunoBernardino** [comment]
@AmoghSaxena I think the commit you make (maybe you'll need to do another PR) needs to be made with your email (if you've made it within GitHub's interface, maybe you need an email associated to your GitHub account), but I'm honestly not sure, I've never had this problem.

**Comment by BrunoBernardino** [comment]
I'm closing this unmerged since it's still not ready and I had to touch this file/lines at https://github.com/padloc/padloc/commit/acb2a3dd8ecd78abd7e8beca2e026b86b67048a9

Thank you so much for letting us know about this @AmoghSaxena !

**Pull request closed without merging**
