### PR TITLE
Turkish (TR) Translation

### PR DESCRIPTION
**Pull request by halacoglu**
I've completed the Turkish translation. Also, I noted down little typos to correct for English language but the `_template.json` file is no longer available and I don't know where every line of translation appears in the app code. How can I correct those now?

Issue: #248

### CODE REVIEW

**Comment by BrunoBernardino** [comment]
Teşekkürler @halacoglu !

As for the English typos, feel free to just report them in a new issue and we'll fix them up!

**Comment by MaKleSoft** [comment]
@BrunoBernardino Can you also add the `_template.json` file back, please?

**Comment by BrunoBernardino** [comment]
Thanks, I hadn't noticed that file had changed. It's back up at https://github.com/padloc/padloc/commit/392faa4d4c1f11f658d9cedad32ae4d331acd234

**Comment by MaKleSoft** [comment]
Thank you, @halacoglu are you on Twitter by any chance? Would love to give you a shout-out for your contribution :)

**Comment by halacoglu** [comment]
> Thank you, @halacoglu! Are you on Twitter by any chance? Would love to give you a shout-out for your contribution :)

I'm `@OsmanHalacoglu` on Twitter, thanks :)

**Pull request merged**
