### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by detobel36**
Added french translation.   

Notice:   
In french there is not a "real" difference between "download" and "upload" (which could be translate by "téléchargement"). So, it's "usual" in french to say "upload".

Linked to issue #248

### CODE REVIEW

**Comment by MaKleSoft** [comment]
Good stuff! Thank you so much! 🥳👍

**Comment by LaunchedBerry07** [comment]
Hi! I'm a newbie on GitHub, so please redirect me, if necessary. I would like to help for the translation into French. My main career is as a translator.

(Btw, the term "téléverser" for "upload" is more accurate than "télécharger" :).)

**Comment by detobel36** [comment]
> (Btw, the term "téléverser" for "upload" is more accurate than "télécharger" :).)
Yes but nobody use it xD

**Comment by LaunchedBerry07** [comment]
> > (Btw, the term "téléverser" for "upload" is more accurate than "télécharger" :).)
> 
> 
> Yes but nobody use it xD       

Indeed, ahah!

**Comment by MaKleSoft** [comment]
@LaunchedBerry07 thanks for offering to help! Unfortunately @detobel36 beat you to it this time but there are new things being added to the app all the time that will require translations as well. I'll be sure to create a new issue when a new batch comes in. Apart from that, reviewing existing translations can never hurt either, especially in the context of the actual UI (I know the texts from the translation file by themselves and without context can be quite ambiguous and hard to translate). Finally another thing that would be helpful would be to curate the [word lists](https://github.com/padloc/padloc/blob/master/packages/locale/res/wordlists/fr.json) used to generate passphrases to make sure there are no strange or (too) offensive words in there (funny/weird is ok). But to be honest, that's such a shitty job that I don't really want to ask anyone to do it 😅

**Comment by LaunchedBerry07** [comment]
@MaKleSoft Ahah! Well, honestly, those tasks don't seem too boring to me! I could help with those, if you want to.

**Pull request merged**
