### PR TITLE
Added Macedonian Translation

### PR DESCRIPTION
**Pull request by andrejdaskalov**
Added ```mk``` locale. Let me know if there's any issues
Issue #248

### CODE REVIEW

**Comment by BrunoBernardino** [comment]
Hi @andrejdaskalov thank you so much for making this contribution! I've noticed this didn't have some tests running for PRs coming from forks that would've caught a few discrepancies, so I'm preparing that here, and after it, you should be able to merge `origin/main` once more, run `npm run locale:extract` locally, and push that again.

**Comment by BrunoBernardino** [comment]
Alright @andrejdaskalov can you please pull/merge/update `origin/main` once more, run `npm run locale:extract`, and then push?

**Comment by BrunoBernardino** [comment]
@andrejdaskalov seems you still need to run `npm run locale:extract` in order to fix the translations file, before pushing. Let me know if you need any help with that.

**Comment by andrejdaskalov** [comment]
@BrunoBernardino I ran ```npm run locale:extract``` but I noticed I have a few new keys in the file and a few missing ones. I'm guessing the command added them? I'm translating those right now, as the tests fail because of missing values.

**Comment by BrunoBernardino** [comment]
@andrejdaskalov that command will add some new strings and might move around some translations. It should still pass with empty values, though (will show English in those cases).

**Comment by BrunoBernardino** [comment]
Thank you so much @andrejdaskalov ! Are you on Twitter by any chance so @MaKleSoft can give you a public shout-out?

**Comment by andrejdaskalov** [comment]
@BrunoBernardino It was my pleasure. And I just created a Twitter account, it's @ADaskalov . Looking forward to contributing to Padloc more in the future!

**Pull request merged**
