### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by pwasiewicz**
Added polish translation.

### CODE REVIEW

**Comment by MaKleSoft** [comment]
@pwasiewicz This looks good to merge, but I still need you to sign the CLA before I can go ahead and merge it. Thanks!

**Comment by pwasiewicz** [comment]
@MaKleSoft  it's strange since I have tried to sign CLA couple of times. At my side looks like it is already signed, but Github doesn't keep up with sync :(
image

**Comment by MaKleSoft** [comment]
@pwasiewicz I think the problem may be that the actual commit was made by a different account: @pwasiewicz-a . Can you try logging in with that account as well to sign the dna?

**Comment by pwasiewicz** [comment]
@MaKleSoft strange, the Github account was the same, but commit author's email is different to Github account one. I'll try to override with --amend as there is no Github account related e-mail used in commit.

**Comment by MaKleSoft** [comment]
@pwasiewicz Hm, the check still doesn't pass but I can see that you did sign the CLA, so I guess this is good to merge. Thank you again for this! I can't stress enough how much I value these contributions. 🙏

**Pull request merged**
