### PR TITLE
Chinese Traditional (Taiwan) Translation

### PR DESCRIPTION
**Pull request by rhuba8324**
Simply as indicated by the title, translation for taiwanese's chinese.

Missing 2 following lines because I currerently don't know where they appears.
"by {0}"
"{0} on {1}"

Linked to https://github.com/padloc/padloc/issues/248

### CODE REVIEW

**Comment by BrunoBernardino** [comment]
Thank you so much @rhuba8324, this is great! The first one appears when showing who last updated an item: https://github.com/padloc/padloc/blob/acb467b25aadd75e8ca195d1ee9fd48945be7c90/packages/app/src/elements/item-view.ts#L552-L558

The second one appears on the device information's description ("Chrome on Windows", for example): https://github.com/padloc/padloc/blob/acb467b25aadd75e8ca195d1ee9fd48945be7c90/packages/app/src/lib/platform.ts#L94-L97

Let me know if you want to address those, otherwise I can just merge this. Thanks again!

**Comment by rhuba8324** [comment]
The translation is now fully completed thanks to your help!
I think it's now ready to be merged, I will still look for improvement for future versions, but it's as good as it gets right now.
:D

**Comment by BrunoBernardino** [comment]
谢谢 @rhuba8324 !

**Comment by MaKleSoft** [comment]
Thanks you so much for your contribution, @rhuba8324! Are you on Twitter by any chance? Would love to give you a shout-out (if that's ok with you).

**Comment by rhuba8324** [comment]
I appreciate that, but I don't have a Twitter account since we rarely use that in where I live.
But I'm okay if you want to do a new locale support announcement simply with my github user name. :D

**Pull request merged**
