### PR TITLE
Add application menu to Tauri app

### PR DESCRIPTION
**Pull request by MaKleSoft**
Fixes https://github.com/padloc/padloc/issues/364

### CODE REVIEW

**Comment by MaKleSoft** [comment]
@BrunoBernardino Can you test how this looks on Linux, please?

**Comment by BrunoBernardino** [comment]
@MaKleSoft all menus were blank (except for File, for which the "Close Window" also didn't work). I hid all menus in Linux and made the Help menu actually work (sending to `https://padloc.app/help/`). I also stopped the electron macos signing for non-prod builds.

I'll check how it works in macos in a bit, and merge if all is good.

**Comment by BrunoBernardino** [comment]
Alright, this worked great in macOS as well, but I saw a couple of things to tweak. Beta builds for Tauri will be at https://github.com/padloc/padloc/actions/runs/1637452749 and for Electron will be at https://github.com/padloc/padloc/actions/runs/1637455226

Once I test those two in Linux and macOS, I'll merge this.

**Comment by BrunoBernardino** [comment]
Electron is working fine in macOS and Ubuntu.

**Comment by MaKleSoft** [comment]
Cool. Let me check windows as well.

**Comment by BrunoBernardino** [comment]
Tauri also works fine in macOS (including copy + paste via shortcuts and clicking) and Ubuntu. I did also notice the logo in macOS is blurred, which doesn't happen in Electron.

**Review by BrunoBernardino — APPROVED** [review]
I haven't confirmed this works on Windows, but I assume it will, otherwise, we can just fix it in another PR. :shipit:

**Comment by MaKleSoft** [comment]
Looks good on Window as well 👍

**Pull request merged**
