### PR TITLE
Update logo and icon

### PR DESCRIPTION
**Pull request by MaKleSoft**
Ok, so after going back and forth for a while and showing the both versions of the logo and icon to a couple of people, I decided to go with the "stacked" one instead of the gradient and drop shadow. The former one simply looks sharper/cleaner and works better in small sizes. It should also fix this issue: https://github.com/padloc/padloc/issues/362

I may keep tweaking it a bit so this is not necessarily the final version, but I still wanted to get this in so I can put it off my mind for now.

### CODE REVIEW

**Comment by MaKleSoft** [comment]
@BrunoBernardino Hm, the web extension build is failing but I'm not sure why. Can you take a look?

**Comment by BrunoBernardino** [comment]
@MaKleSoft looks like we're running into https://github.com/cardinalby/webext-buildtools-chrome-crx-action/issues/10 see there for a quick/hotfix in `package.json` if you need it.

**Comment by MaKleSoft** [comment]
Hm, I guess we could also just ignore it, right? Since I assume this is going to be fixed soon, anyway.

**Comment by BrunoBernardino** [comment]
Definitely not a blocker, just can't build web/chrome extension automatically for now.

**Pull request merged**
